apiVersion: extensions/v1beta1
kind: "Deployment"
metadata:
  name: mitm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mitm
  template:
    metadata:
      labels:
        app: mitm
    spec:
      containers:
      - name: mitm
        image: mitmproxy/mitmproxy:latest
        command: ["docker-entrypoint.sh"]
        args: ["mitmdump", "-s", "/usr/share/mitm/addons.py"]
        ports:
        - containerPort: 8080
        - containerPort: 8081
        volumeMounts:
        - name: mitm
          mountPath: "/home/mitmproxy/.mitmproxy"
        - name: mitm-addon
          mountPath: /usr/share/mitm
      volumes:
      - name: mitm
        persistentVolumeClaim:
          claimName: mitm
      - name: mitm-addon
        configMap:
          name: mitm-configmap
          items:
            - key: addons.py
              path: addons.py
