kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch
  annotations:
    volume.beta.kubernetes.io/storage-class: vsphere-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
