apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kibana
  namespace: elk
spec:
  secretName: kibana-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kibana.high.am
  dnsNames:
  - kibana.high.am
  acme:
    config:
    - dns01:
        provider: clouddns
      domains:
      - kibana.high.am
